version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-dma:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  redis:
    image: redis:6
    volumes:
      - redis-dma:/data
    restart: unless-stopped
    ports:
    - 6379:6379


volumes:
  postgres-dma:
    external: true
  redis-dma:
    external: true